name: 歌词请愿
description: 我想要一个歌曲能有 TTML 歌词！
title: "[歌词请愿] "
labels: ["歌词请愿"]
body:
  - type: markdown
    attributes:
      value: |
        在创建 Issue 前，请确认歌词确实从来没有人提交过哦！
  - type: input
    id: song-name
    attributes:
      label: 歌曲名称
      description: 推荐使用 歌手 - 歌曲 格式，方便仓库管理员确认你的歌曲是否存在
      placeholder: YOASOBI - 群青
    validations:
      required: true
  - type: input
    id: song-id
    attributes:
      label: 音乐对应的音乐平台和音乐 ID
      description: |
        提供 ID 能帮助歌词制作者更好地找到你需要请愿歌词的歌曲
        如果歌曲存在其他变体（例如伴奏），可以以英文逗号分隔多个 ID
      placeholder: "1472480890"
    validations:
      required: true
  - type: checkboxes
    id: others
    attributes:
      label: 其他备注
      description: 如果可以确认其他信息的话也会对歌词制作有所帮助哦
      options:
        - label: 这个歌曲在 Apple Music 上有逐词歌词
  - type: textarea
    id: comment
    attributes:
      label: 备注
      description: 还有什么需要补充说明的吗？
    validations:
      required: false
