name: 提交/修正歌词
description: 我想提交/修正一个歌曲的 TTML 歌词文件！
title: "[歌词提交/修正] "
labels: ["歌词提交/补正"]
assignees:
  - Steve-xmh
body:
  - type: input
    id: ttml-download-url
    attributes:
      label: TTML 歌词文件下载直链
      description: |
        Github Action 将会获取该链接指向的歌词文件数据并检查正确性
        确认无误后，Github Action 机器人将会在该 Issue 下方评论歌词文件数据原文供留存检查
        如果访问出错或格式有误，会导致你的 Issue 被直接关闭，请注意哦！
    validations:
      required: true
  - type: dropdown
    id: upload-reason
    attributes:
      label: 提交缘由
      description: 是一首新歌曲的歌词呢？还是原来的歌词有疏漏或者错误呢？
      options:
        - 新歌词提交
        - 修正已有歌词
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: 备注
      description: |
        有什么需要补充说明的呢？
        如果你所提交的歌曲中包含因特殊原因无法直接播放或获取的歌曲，建议提供一个音源下载链接，音质不做要求但是必须准确，这样可以方便审核哦！
    validations:
      required: false
