name: 自动关闭重复PR

on:
  issue_comment:
    types: [created]  # 监听评论创建事件

jobs:
  close-duplicate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Close PR and delete branch if "!duplicate" command is used
        if: startsWith(github.event.comment.body, '!duplicate')
        run: |
          # 提取评论中的 PR 编号
          echo "Admin detected !duplicate command, processing duplicates"
          pr_numbers=$(echo "${{ github.event.comment.body }}" | grep -o '#[0-9]*' | sed 's/#//g')
          for pr_number in $pr_numbers; do
            echo "Closing duplicate PR #$pr_number"
            gh pr close $pr_number
            gh pr delete $pr_number --confirm
          done

env:
  GITHUB_TOKEN: ${ secrets.GITHUB_TOKEN }}
